server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**

        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
